const { app, BrowserWindow, shell } = require('electron');
const path = require('path');

let mainWindow;

function createWindow() {
  mainWindow = new BrowserWindow({
    width: 1280,
    height: 800,
    minWidth: 800,
    minHeight: 600,
    show: false, // Don't show until ready-to-show
    backgroundColor: '#0f172a',
    autoHideMenuBar: true, // Professional look
    icon: path.join(__dirname, 'assets/icon.png'),
    webPreferences: {
      nodeIntegration: false,
      contextIsolation: true,
      sandbox: true,
    },
  });

  const { dialog } = require('electron');

  // Load the live URL
  mainWindow.loadURL('https://hadhghwhdwhdjnjwd.vercel.app/shift-reports/manager').catch((err) => {
    dialog.showErrorBox(
      'Connection Error',
      'Failed to connect to the cloud server at https://hadhghwhdwhdjnjwd.vercel.app/.\n\nPlease ensure your device is connected to the internet.'
    );
  });

  // Show window gracefully when loaded
  mainWindow.once('ready-to-show', () => {
    mainWindow.show();
    // Open DevTools automatically
    mainWindow.webContents.openDevTools();
  });

  // Log console messages from the renderer to the terminal
  mainWindow.webContents.on('console-message', (event, level, message, line, sourceId) => {
    console.log(`[Electron Console] Level ${level}: ${message} (at ${sourceId}:${line})`);
  });

  // Handle external links (e.g. print popups) securely
  mainWindow.webContents.setWindowOpenHandler(({ url }) => {
    // We allow popups for the print window generated by JS
    return { action: 'allow' };
  });

  mainWindow.on('closed', function () {
    mainWindow = null;
  });
}

app.whenReady().then(() => {
  createWindow();

  app.on('activate', function () {
    if (BrowserWindow.getAllWindows().length === 0) createWindow();
  });
});

app.on('window-all-closed', function () {
  if (process.platform !== 'darwin') app.quit();
});
