const { app, BrowserWindow, shell } = require('electron');
const path = require('path');

let mainWindow;

function createWindow() {
  mainWindow = new BrowserWindow({
    width: 1280,
    height: 800,
    minWidth: 800,
    minHeight: 600,
    show: false, // Don't show until ready-to-show
    backgroundColor: '#0f172a',
    autoHideMenuBar: true, // Professional look
    webPreferences: {
      nodeIntegration: false,
      contextIsolation: true,
      sandbox: true,
    },
  });

  // Load the live Next.js Vercel URL
  mainWindow.loadURL('https://anhreports.vercel.app/');

  // Show window gracefully when loaded
  mainWindow.once('ready-to-show', () => {
    mainWindow.show();
  });

  // Handle external links (e.g. print popups) securely
  mainWindow.webContents.setWindowOpenHandler(({ url }) => {
    // We allow popups for the print window generated by JS
    return { action: 'allow' };
  });

  mainWindow.on('closed', function () {
    mainWindow = null;
  });
}

app.whenReady().then(() => {
  createWindow();

  app.on('activate', function () {
    if (BrowserWindow.getAllWindows().length === 0) createWindow();
  });
});

app.on('window-all-closed', function () {
  if (process.platform !== 'darwin') app.quit();
});
